language: php

notifications:
  email:
    recipients:
    - dmitriim@catalyst-au.net

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

addons:
   postgresql: "9.4"

matrix:
  include:
    # PHP 7.0
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_34_STABLE
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_34_STABLE
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_36_STABLE
    # PHP 7.1
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_34_STABLE
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=MOODLE_34_STABLE
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=MOODLE_36_STABLE
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=master
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=master
    # PHP 7.2
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_34_STABLE
    - php: 7.2
      env: DB=pgsql MOODLE_BRANCH=MOODLE_34_STABLE
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.2
      env: DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
    - php: 7.2
      env: DB=pgsql MOODLE_BRANCH=MOODLE_36_STABLE
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=master
    - php: 7.2
      env: DB=pgsql MOODLE_BRANCH=master

before_install:
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install -vvv

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci csslint
  - moodle-plugin-ci shifter
  - moodle-plugin-ci jshint
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
